// <auto-generated />
using System;
using LeoDevTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeoDevTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520010735_AddCamposTrabalhoReflexao")]
    partial class AddCamposTrabalhoReflexao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeoDevTracker.API.Models.AnaliseSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("SemanaFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SemanaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("analises_semanais", (string)null);
                });

            modelBuilder.Entity("LeoDevTracker.API.Models.MetaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMeta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("metas_financeiras", (string)null);
                });

            modelBuilder.Entity("LeoDevTracker.API.Models.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Percentual")
                        .HasColumnType("integer");

                    b.Property<string>("Stack")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("LeoDevTracker.API.Models.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BugsRift")
                        .HasColumnType("integer");

                    b.Property<string>("Conquistas")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Desafios")
                        .HasColumnType("text");

                    b.Property<string>("Destaque")
                        .HasColumnType("text");

                    b.Property<int>("FeaturesRift")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HorasEstudo")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HorasTrabalhadas")
                        .HasColumnType("numeric");

                    b.Property<int?>("Humor")
                        .HasColumnType("integer");

                    b.Property<int?>("TicketsTrabalhados")
                        .HasColumnType("integer");

                    b.Property<string>("TopicoEstudo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TreinoObs")
                        .HasColumnType("text");

                    b.Property<int?>("TreinoRendimento")
                        .HasColumnType("integer");

                    b.Property<string>("TreinoTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("registros_diarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
